@startuml
title 基于类似于GitHub平台的实验管理平台--用例图
actor teachers
actor students
actor users
actor admin

users <|-- teachers
users <|-- students
users <|-- admin

package 用户用例集 {
users --up-> (登录)
users --up-> (登出)
users --up-> (查看用户信息)
users --up-> (修改用户信息)
users --up-> (修改密码)
}
package 业务用例集 {
teachers ---> (成绩管理)
teachers ---> (评定成绩)
teachers ---> (学生列表)
teachers ---> (课程管理)

students ---> (查看课程成绩)
students ---> (课程管理)
students ---> (绑定账号)
admin ---> (课程管理)
admin ---> (老师管理)
admin ---> (系统设置)
}


@enduml