@startuml
actor ":读者"
actor ":图书管理员"
":读者"->"图书列表" :1. 查询图书
activate "图书列表"
activate ":读者"
"图书列表"->"图书" :2. 选择图书
activate "图书"
"图书"->":读者" : 3.选择图书成功
deactivate "图书"
deactivate "图书列表"
deactivate ":读者"
loop

":读者"->":图书管理员" :4.提交借阅书籍
activate ":读者"
activate ":图书管理员"
":图书管理员" ->"借书界面" :5.处理图书
activate "借书界面"

"借书界面"->":借书信息" :6.获取图书信息
activate ":借书信息"
":借书信息"->"借书界面" :7.图书信息
deactivate ":借书信息"
deactivate "借书界面"

":系统"<-"借书界面" :8.增加借阅记录
activate "借书界面"
activate ":系统"

":系统" -> ":系统" : 9.检查图书剩余量
":系统" -> ":系统" : 10.检查读者可借图书本数
":系统"-> "借书界面" : 11.增加借阅记录成功
"借书界面" ->":图书管理员" :12.借阅成功
":图书管理员"->":读者" :13.允许读者带走书籍
deactivate ":系统"
deactivate "借书界面"
deactivate ":读者"
deactivate ":图书管理员"
end
@enduml