@startuml
actor ":系统管理员"

":系统管理员"->"显示图书管理员列表" : 1.查看图书管理员
activate ":系统管理员"
activate "显示图书管理员列表"
loop 删除图书管理员
"显示图书管理员列表" ->"系统" : 2.删除图书管理员
activate "系统"
"系统" ->"系统" :3. 确认删除
"系统" ->"显示图书管理员列表" : 4.删除成功
deactivate "系统"
deactivate "显示图书管理员列表"
end
loop 增加图书管理员
"显示图书管理员列表"->"系统"  : 5.增加图书管理员
activate "显示图书管理员列表"
activate "系统"
"系统" ->"用户详细信息"  : 6. 输入新增图书管理员信息
activate "用户详细信息"
"系统" <-"用户详细信息" : 7.输入信息提交给系统
deactivate "用户详细信息"
"系统"->"系统" :8.增加图书管理员
"系统" ->"显示图书管理员列表" :9.增加成功
deactivate "系统"
deactivate "显示图书管理员列表"
end
deactivate ":系统管理员"
@enduml