@startuml
actor ":图书管理员"

":图书管理员"->"显示图书列表界面" : 1.登陆
activate ":图书管理员"
activate "显示图书列表界面"
"显示图书列表界面"->"显示图书详细界面" : 2.查看详情
activate "显示图书详细界面"
loop 修改图书信息操作
"显示图书详细界面"->"系统" : 3.修改图书信息
activate "系统"
"系统"->"系统" :4.修改是否符合规范
系统->"显示图书详细界面" : 5 .修改成功
end
deactivate "系统"
deactivate "显示图书详细界面"
loop 增加图书操作
"显示图书列表界面"->"系统" :6.增加图书
activate "系统"
"系统"->"显示图书详细界面" :7.输入增加图书的详细信息
"系统"<-"显示图书详细界面" :8.提交
"系统"->"系统" :9. 检查输入是否有效
"系统"->"显示图书列表界面" :10.增加成功
deactivate "系统"
end
loop 删除图书操作
"显示图书列表界面" ->"系统" : 11.删除图书
activate "系统"
"系统"->"系统" :12.确认删除
"系统"->"显示图书列表界面" : 13.删除成功
deactivate "系统"
end
"显示图书列表界面"->":图书管理员" :14.注销
deactivate "显示图书列表界面"
deactivate ":图书管理员"
@enduml