@startuml
actor ":读者"
actor ":图书管理员"
loop
":读者"->":图书管理员" :1.提交归还书籍
activate ":读者"
activate ":图书管理员"
":图书管理员" ->"还书界面" :2.处理图书
activate "还书界面"

"还书界面"->":还书信息" :3.获取图书信息
activate ":还书信息"
":还书信息"->"还书界面" :4.图书信息
deactivate ":还书信息"
deactivate "还书界面"

":系统"<-"还书界面" :5.删除借阅记录
activate "还书界面"
activate ":系统"

":系统" -> ":系统" : 6.检查是否过期
":系统" -> ":系统" : 7.删除借阅记录
":系统"-> "还书界面" : 8.删除记录成功
deactivate ":系统"
"还书界面"->":图书管理员" :9.处理图成功
deactivate "还书界面"
":图书管理员"->":读者" :10.还书成功
deactivate ":图书管理员"
deactivate ":读者"
end
@enduml