@startuml
left to right direction
skinparam packageStyle rectangle
actor 图书管理员
actor 读者
actor 系统管理员
rectangle  {

  图书管理员-->(借出图书)
  图书管理员-->(归还图书)
  图书管理员-->(维护图书)
  图书管理员-->(维护读者信息)
  图书管理员-->(增加或者删除图书)
  (查询书目) <-- 读者
  (查询借阅情况) <-- 读者
  (预定图书) <-- 读者
  (取消预订) <-- 读者
  (维护读者信息)<--读者
  系统管理员-->(增加或删除读者权限)
  系统管理员-->(系统维护)
  系统管理员-->(维护图书管理员信息)

}
@enduml